### ISSUE TITLE
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

### ISSUE THREAD

**Issue by alonsoir** [thammegowda/tensorflow-grpc-java#8]
I've noticed that the project with this code and dependencies doesn't work, it doesn't matter to fix the MANIFEST.mf file, it gives an exception like this:

/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=55919:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/tools.jar:/Users/aironman/gitProjects/tensorflow-grpc-java/target/classes:/Users/aironman/.m2/repository/com/google/protobuf/protobuf-java/3.0.0-beta-3/protobuf-java-3.0.0-beta-3.jar:/Users/aironman/.m2/repository/io/grpc/grpc-all/1.25.0/grpc-all-1.25.0.jar:/Users/aironman/.m2/repository/io/grpc/grpc-api/1.25.0/grpc-api-1.25.0.jar:/Users/aironman/.m2/repository/com/google/errorprone/error_prone_annotations/2.3.3/error_prone_annotations-2.3.3.jar:/Users/aironman/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/aironman/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar:/Users/aironman/.m2/repository/io/grpc/grpc-auth/1.25.0/grpc-auth-1.25.0.jar:/Users/aironman/.m2/repository/com/google/auth/google-auth-library-credentials/0.17.1/google-auth-library-credentials-0.17.1.jar:/Users/aironman/.m2/repository/io/grpc/grpc-core/1.25.0/grpc-core-1.25.0.jar:/Users/aironman/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar:/Users/aironman/.m2/repository/com/google/android/annotations/4.1.1.4/annotations-4.1.1.4.jar:/Users/aironman/.m2/repository/io/perfmark/perfmark-api/0.19.0/perfmark-api-0.19.0.jar:/Users/aironman/.m2/repository/io/opencensus/opencensus-api/0.21.0/opencensus-api-0.21.0.jar:/Users/aironman/.m2/repository/io/opencensus/opencensus-contrib-grpc-metrics/0.21.0/opencensus-contrib-grpc-metrics-0.21.0.jar:/Users/aironman/.m2/repository/io/grpc/grpc-context/1.25.0/grpc-context-1.25.0.jar:/Users/aironman/.m2/repository/io/grpc/grpc-okhttp/1.25.0/grpc-okhttp-1.25.0.jar:/Users/aironman/.m2/repository/com/squareup/okio/okio/1.13.0/okio-1.13.0.jar:/Users/aironman/.m2/repository/com/squareup/okhttp/okhttp/2.5.0/okhttp-2.5.0.jar:/Users/aironman/.m2/repository/io/grpc/grpc-testing/1.25.0/grpc-testing-1.25.0.jar:/Users/aironman/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/aironman/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/aironman/.m2/repository/io/grpc/grpc-protobuf/1.25.0/grpc-protobuf-1.25.0.jar:/Users/aironman/.m2/repository/com/google/guava/guava/28.1-android/guava-28.1-android.jar:/Users/aironman/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/Users/aironman/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/aironman/.m2/repository/org/checkerframework/checker-compat-qual/2.5.5/checker-compat-qual-2.5.5.jar:/Users/aironman/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/Users/aironman/.m2/repository/com/google/api/grpc/proto-google-common-protos/1.12.0/proto-google-common-protos-1.12.0.jar:/Users/aironman/.m2/repository/io/grpc/grpc-protobuf-lite/1.25.0/grpc-protobuf-lite-1.25.0.jar:/Users/aironman/.m2/repository/io/grpc/grpc-stub/1.25.0/grpc-stub-1.25.0.jar:/Users/aironman/.m2/repository/io/grpc/grpc-netty/1.25.0/grpc-netty-1.25.0.jar:/Users/aironman/.m2/repository/io/netty/netty-codec-http2/4.1.42.Final/netty-codec-http2-4.1.42.Final.jar:/Users/aironman/.m2/repository/io/netty/netty-common/4.1.42.Final/netty-common-4.1.42.Final.jar:/Users/aironman/.m2/repository/io/netty/netty-buffer/4.1.42.Final/netty-buffer-4.1.42.Final.jar:/Users/aironman/.m2/repository/io/netty/netty-transport/4.1.42.Final/netty-transport-4.1.42.Final.jar:/Users/aironman/.m2/repository/io/netty/netty-resolver/4.1.42.Final/netty-resolver-4.1.42.Final.jar:/Users/aironman/.m2/repository/io/netty/netty-codec/4.1.42.Final/netty-codec-4.1.42.Final.jar:/Users/aironman/.m2/repository/io/netty/netty-handler/4.1.42.Final/netty-handler-4.1.42.Final.jar:/Users/aironman/.m2/repository/io/netty/netty-codec-http/4.1.42.Final/netty-codec-http-4.1.42.Final.jar:/Users/aironman/.m2/repository/io/netty/netty-handler-proxy/4.1.42.Final/netty-handler-proxy-4.1.42.Final.jar:/Users/aironman/.m2/repository/io/netty/netty-codec-socks/4.1.42.Final/netty-codec-socks-4.1.42.Final.jar:/Users/aironman/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Users/aironman/.m2/repository/org/slf4j/slf4j-api/1.7.29/slf4j-api-1.7.29.jar:/Users/aironman/.m2/repository/org/slf4j/slf4j-simple/1.7.29/slf4j-simple-1.7.29.jar:/Users/aironman/.m2/repository/org/slf4j/slf4j-log4j12/1.7.29/slf4j-log4j12-1.7.29.jar:/Users/aironman/.m2/repository/org/slf4j/slf4j-jdk14/1.7.29/slf4j-jdk14-1.7.29.jar:/Users/aironman/.m2/repository/org/slf4j/slf4j-nop/1.7.29/slf4j-nop-1.7.29.jar:/Users/aironman/.m2/repository/org/slf4j/slf4j-jcl/1.7.29/slf4j-jcl-1.7.29.jar:/Users/aironman/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar edu.usc.irds.tensorflow.grpc.Main localhost:9090 src/main/resources/ferrari.jpg
Creating channel host: localhost port= 9090
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/aironman/.m2/repository/org/slf4j/slf4j-simple/1.7.29/slf4j-simple-1.7.29.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/aironman/.m2/repository/org/slf4j/slf4j-log4j12/1.7.29/slf4j-log4j12-1.7.29.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/aironman/.m2/repository/org/slf4j/slf4j-jdk14/1.7.29/slf4j-jdk14-1.7.29.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/aironman/.m2/repository/org/slf4j/slf4j-nop/1.7.29/slf4j-nop-1.7.29.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/aironman/.m2/repository/org/slf4j/slf4j-jcl/1.7.29/slf4j-jcl-1.7.29.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
Channel initialized! ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=1, target=localhost:9090}}
TODO: test channel here with a sample image
Image = src/main/resources/ferrari.jpg
Something went WRONG! UNAVAILABLE: io exception
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
	at edu.usc.irds.tensorflow.grpc.InceptionBlockingStub.classify(InceptionBlockingStub.java:64)
	at edu.usc.irds.tensorflow.grpc.TensorflowObjectRecogniser.recognise(TensorflowObjectRecogniser.java:70)
	at edu.usc.irds.tensorflow.grpc.Main.main(Main.java:55)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:9090
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code 255

I've tried to update the version of the dependencies, specifically:

        <grpc.version>1.25.0</grpc.version>
used by :
grpc-all
grpc-protobuf
grpc-stub
grpc-netty

I think this last one, Betty's, is the one that's making trouble. Can I ask how you solved it? Because when I try to run your Docker version, I see that it works, but I suspect that it doesn't have the same code or dependencies that you put in this repository. Can you shed some light, please?

My branch is located in https://github.com/alonsoir/tensorflow-grpc-java/tree/feature-Dockerfile

**Comment by alonsoir** [comment]
Ok, this code represents a client, not the grpc server. The server is located in Docker container.
